### ISSUE TITLE
Reset retweet interval when tweet is already retweeted

### ISSUE THREAD

**Issue by Tinismo** [buluba89/Yatcobot#17]
Suppose I accidentally deleted the ignorelist file, it is possible to reset retweet interval instead of waiting 600 seconds when a tweet is already retweeted ?
`yatcobot.bot - ERROR - Alredy retweeted tweet with id ...`

**Comment by buluba89** [comment]
@Tinismo 
One quick hack would be to change the interval to a small number in the config (like 10) until it finds
tweets that it hasn't retweet.
I could add an option to continue retweeting posts until it find one that is new. I am little afraid of because it may trigger bot detection.
Maybe i could fetch the accounts retweets from the api (i an not sure if the api gives you that option, but probably it does), but this will also make a lot of api calls that makes me uncomfortable

Any other ideas ?

**Comment by buluba89** [comment]
Also another more permanent solution to this i was thinking is to change the ignorelist file to an database so it can store data more safeley.

**Comment by buluba89** [comment]
@Tinismo 
I made a config option for skipping retweed post. Pleaze try it and report any problems !
